homepageku/urls.py
from django.urls import path
from . import views

app_name = 'homepageku'

urlpatterns = [
    path('story1/', views.kucing, name='index')
]

personalwebsite/urls.py
from django.urls import path
from . import views

app_name = 'personalwebsite'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('profil/', views.index, name='index'),
    path('education/', views.newpage, name='education')
]

punyaferika/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story1/', include('homepageku.urls', namespace='story-1')),
    path('', include('personalwebsite.urls', namespace='personalwebsite')),
    path('storylima/', include('storylima.urls', namespace='storylima')),
    path('story6/', include('storyenam.urls', namespace='storyenam')),
]

storyenam/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import pilih, addKegiatan, listKegiatan, daftar, deleteUser

app_name = 'storyenam'

urlpatterns = [
    path('', pilih, name='pilih'),
    path('addKegiatan/', addKegiatan, name='addKegiatan'),
    path('listKegiatan/', listKegiatan, name='listKegiatan'),
    path('daftar/<int:task_id>/', daftar, name='daftar'),
    path('delete/<int:delete_id>/', deleteUser, name='delete'),
]

storylima/urls.py
from django.urls import path
from . import views

app_name = 'storylima'

urlpatterns = [
    path('storylima',views.listMatkul,name='listMatkul'),
    path('TambahkanMatkul',views.add, name='add'),
    path('delete/P<int:delete_id>/',views.delete, name='delete'),
]

homepageku/models.py
from django.db import models

# Create your models here.

personalwebsite/models.py
from django.db import models

# Create your models here.

storyenam/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100)
    deskripsi = models.CharField(max_length=1000)

    def __str__(self):
        return self.nama_kegiatan


class Daftar(models.Model):
    nama = models.CharField(max_length=100)
    kegiatan = models.ForeignKey(Kegiatan,
                                 on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.nama

storylima/models.py
from django.db import models

# Create your models here.

class PostModel(models.Model):
    nama_matkul = models.CharField(max_length = 100)
    nama_dosen = models.CharField(max_length=100)
    jumlah_sks = models.IntegerField()
    semester = models.CharField(max_length = 100)
    ruang_kelas = models.CharField(max_length = 100)
    deskripsi = models.CharField(max_length = 100, null = True)
    
    def __str__(self):
        return "{}.{}".format(self.id, self.nama_matkul)

storyenam/forms.py
from django import forms

class FormKegiatan(forms.Form):
    nama_kegiatan = forms.CharField(
        label="Nama kegiatan",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control w-60',
            }
        )
    )

    deskripsi = forms.CharField(
        label="Deskripsi kegiatan",
        max_length=1000,
        widget=forms.Textarea(
            
        )
    )

class FormDaftar(forms.Form):
    nama = forms.CharField(
        label="Your Name",
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
 

storylima/forms.py
from django import forms
from .models import PostModel


class MatkulForm(forms.Form):
    nama_matkul = forms.CharField(
        label = "Nama Mata Kuliah",
        max_length = 100,
        widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    nama_dosen = forms.CharField(
    label = "Nama Dosen",
    max_length = 100,
    widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    jumlah_sks = forms.IntegerField(
        label = "Jumlah SKS",
        widget = forms.NumberInput(
            attrs={
                'class':'form-control',
                'min':'1',
                'max':'6',
                'type':'number'
            }
        )
    )
    semester = forms.CharField(
    label = "Semester Tahun",
    max_length = 100,
    widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    ruang_kelas = forms.CharField(
    label = "Ruang Kelas",
    max_length = 100,
    widget = forms.TextInput(
            attrs={
                'class':'form-control',
            }
        )
    )
    deskripsi = forms.CharField(
    label = "Deskripsi",
    max_length = 100,
    widget = forms.Textarea(
            attrs={
                'class':'form-control',
            }
        )
    )

homepageku/views.py
from django.shortcuts import render

# Create your views here.
def kucing(request):
    return render(request, "story1.html")

personalwebsite/views.py
from django.shortcuts import render

# Create your views here.

def welcome(request):
    return render(request, 'personalwebsite/welcome.html')

def index(request):
    return render(request, 'personalwebsite/index.html')

def newpage(request):
    return render(request, 'personalwebsite/newpage.html')

storyenam/views.py
from django.shortcuts import render,redirect
from .forms import FormKegiatan, FormDaftar
from .models import Kegiatan, Daftar
# Create your views here.

def pilih(request):
    return render(request, 'storyenam/pilih.html')

def addKegiatan(request):
    form_kegiatan = FormKegiatan(request.POST or None)
    if request.method == "POST":
        if form_kegiatan.is_valid():
            Kegiatan.objects.create(
                nama_kegiatan = form_kegiatan.cleaned_data.get('nama_kegiatan'),
                deskripsi = form_kegiatan.cleaned_data.get('deskripsi'),
                )
            return redirect('/story6/')
    
    context = {
        'form_kegiatan': form_kegiatan,
    }
    return render(request, 'storyenam/addKegiatan.html', context)

def listKegiatan(request):
    kegiatan = Kegiatan.objects.all()
    daftar = Daftar.objects.all()
    context= {
        'kegiatan': kegiatan,
        'daftar': daftar,
    }
    return render(request, 'storyenam/listKegiatan.html', context)

def deleteUser(request, delete_id):
    kegiatan = Kegiatan.objects.all()
    daftar = Daftar.objects.all()
    print(delete_id)
    daftar_to_delete = Daftar.objects.get(id=delete_id)
    daftar_to_delete.delete()
    return redirect('/story6/listKegiatan')


def daftar(request, task_id):
    form_nama = FormDaftar()

    if request.method == "POST":
        form_nama_input = FormDaftar(request.POST)
        if form_nama_input.is_valid():
            data = form_nama_input.cleaned_data
            orangBaru = Daftar()
            orangBaru.nama = data['nama']
            orangBaru.kegiatan = Kegiatan.objects.get(id=task_id)
            orangBaru.save()
            return redirect('/story6/listKegiatan')
    context={
        'form_nama': form_nama,
    }
    return render(request, 'storyenam/daftar.html', context)

storylima/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import MatkulForm
from .models import PostModel
# Create your views here.

def delete(request,delete_id):
	PostModel.objects.filter(id=delete_id).delete()
	return redirect('storylima:listMatkul')
    
def listMatkul(request):
    posts = PostModel.objects.all()
    context = {
        'page_title':'List Mata Kuliah',
        'posts':posts,
    }
    return render(request, 'storylima/listMatkul.html',context)

def add(request):
    matkul_form = MatkulForm(request.POST or None)

    if matkul_form.is_valid():
        if request.method == 'POST':
            PostModel.objects.create(
                nama_matkul = matkul_form.cleaned_data.get('nama_matkul'),
                nama_dosen = matkul_form.cleaned_data.get('nama_dosen'),
                jumlah_sks = matkul_form.cleaned_data.get('jumlah_sks'),
                semester = matkul_form.cleaned_data.get('semester'),
                ruang_kelas = matkul_form.cleaned_data.get('ruang_kelas'),
                deskripsi = matkul_form.cleaned_data.get('deskripsi'),
                )
            return HttpResponseRedirect("/storylima/storylima")

            

    context = {
        'page_title':'Tambahkan Mata Kuliah',
        'matkul_form':matkul_form,
    }
    return render(request, 'storylima/add.html', context)
    

personalwebsite/templates/personalwebsite/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;669;800;900&display=swap" rel="stylesheet">

    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!--Icon-->
    <link rel="icon" type="image/png" href="{% static 'sunflower.png' %}">

    <!--icon library-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Ferika's Personal Website</title>
  </head>

<body>
   
<!-- Navigation Bar -->
<div class="offset-1 col-10 text-center">
    <nav class="navbar fixed-top navbar-expand-lg navbar-light">
        <a class="navbar-brand active" href="{% url 'personalwebsite:welcome' %}">Ferika <img src="{% static 'sunflower.png' %}" width="30px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#home">Home</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#about">About</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#skill">Skills</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#experience">Experience</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#interest">Interest</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#hobby">Hobby</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#contact">Contact</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'personalwebsite:index' %}#hobby">Feedback</a>
            </li> 
            <li class="nav-item">
            <a class="nav-link" href="{% url 'story-1:index' %}">Story 1</a>    
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'storylima:listMatkul' %}">Story 5</a>    
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'storyenam:pilih' %}">Story 6</a>    
            </li>
        </ul>
        </div>
    </nav>
    </div>

    <!-- Block Main -->
    {% block main %} {% endblock main %}



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

personalwebsite/templates/personalwebsite/welcome.html
{% extends 'personalwebsite/base.html' %} {% load static %}

{% block main %}
  <!--Text Section-->
    <div class="text-align-center" id="welcome" <a href="{% url 'personalwebsite:index' %}"></a>
      <div class="centered" id="first">
        <div class="row">
          <div class="col-md-1">
          </div>
          <div class="col-md-11">
            <a href="{% url 'personalwebsite:index' %}">
              <p class="wadah-mengetik">
                Hello there,<br>This is Ferika's personal website<br>Want to know more about Ferika?<br>Just tap me!<br>
              </p>
            </a>
          </div>
        </div>
      </div>
      <img src="{% static 'rerumputan.png' %}" class="yumput" width="100%">
    </div>

{% endblock main %}

storyenam/templates/storyenam/addKegiatan.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
            background-color: #f7bacc;
            font-family: 'Playfair Display', serif;
        }
        a {
            color: rgb(248, 255, 189);
        }
        #back a{
            color: brown;
        }
        card {
            background-color: cornflowerblue;
        }
        #buttonsubmit {
            background-color: crimson;
            color: aliceblue;
        }

    </style>
    <title>Story 6 | tambah Kegiatan</title>
  </head>
  <body> 
    
    <div class="row mt-2 mb-3 justify-content-center">
        <div class="col text-center">
          <button id="back" type="button" class="btn btn-outline-warning"><a href="{% url 'personalwebsite:welcome' %}">Kembali ke halaman utama</a></button>
        </div>
    </div>
        
        <div class="row mt-3 mb-3">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="card">
                    <h5 class="card-header">Tambah Mata kuliah</h5>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                    
                            {{form_kegiatan.nama_kegiatan.label_tag}}
                            {{form_kegiatan.nama_kegiatan}}
                      
                            {{form_kegiatan.deskripsi.label_tag}} <br>
                            {{form_kegiatan.deskripsi}}
                            <br>
                            <button id="buttonsubmit" class="btn" type="submit">Tambah Kegiatan</button>
            
                        </form>            
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
        <div class="row mb-3 justify-content-center">
            <div class="col text-center">
              <button type="button" class="btn btn-info"><a href="{% url 'storyenam:listKegiatan' %}">Lihat list kegiatan</a></button>
            </div>
        </div>









    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

storyenam/templates/storyenam/listKegiatan.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;669;800;900&display=swap" rel="stylesheet">
    
    <style>
      body {
        background-color: #d3bfeb;
        font-family: 'Playfair Display', serif;
      }
      a {
      color: rgb(69, 4, 107);
      }
      h1 {
        color: rgb(83, 61, 104);
      }
      #buttonregist{
        background-color: darkmagenta;
        color: aliceblue;
      }
      #buttondel{
        background-color: hotpink;
      }

    </style>
    <title>Story 6</title>
  </head>
  <body>
    <section class="container-fluid d-flex flex-wrap align-content-center mt-5">
      <div  class="section-title mx-auto text-center mt-5">
          <div class="flex-col">
              <a href="{% url 'storyenam:pilih' %}">Back to add activities</a>
              <h1 class="text-md">List Activities</h1>
  
          </div>
        </div>
  
\
        <div class="row w-100 justify-content-center">
          {% for kegiatannya in kegiatan %}
          <div class=" col-md-4 m-4 p-4">
            <ul class="list-group">
              <li class="list-group-item text-center"><b>{{ kegiatannya.nama_kegiatan }}</b> </li>
              {% for namanya in daftar %}
              {% if namanya.kegiatan == kegiatannya %}
              <li class="list-group-item">
                <div class="d-flex justify-content-between">
                  {{ namanya.nama }}
                  <a href="{% url 'storyenam:delete' delete_id=namanya.pk %}" class="btn btn-light"><button  id="buttondel" class="btn">Delete</button></a>
                </div>
              </li>
              {% endif %}
              {% endfor %}
              <li class="list-group-item text-center"><a href="{% url 'storyenam:daftar' task_id=kegiatannya.pk %}" ><button class="btn" id="buttonregist">Register</button></a></li>
            </ul>
          </div>
          {% endfor %}
        </div>







    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

storyenam/templates/storyenam/pilih.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <style>
            body {
                background-color: #FFFEDF;
                font-family: 'Playfair Display', serif;
            }
            .marg {
                margin-top: 20vw;
                width: auto;
            }

        </style>
        <title>Story 6</title>
    </head>
    <body>
    
    <div class="marg"></div>
    
    <div class="row justify-content-center mt-5 mb-5">
        <div class="col-md-4"> 
            <a href="{% url 'storyenam:addKegiatan'%}" class="btnMatkul text-sm-center">
            <div class="alert alert-primary" role="alert">
                <h1 class="alert-heading">Tambah Kegiatan!</h1>
                <p>Tambahkan kegiatan yang ingin kamu buat!</p>
                <hr>
            </div>
            </a>
        </div>
        <div clas="col-md-2"></div>
        <div class="col-md-4">
            <a href="{% url 'storyenam:listKegiatan'%}" class="btnMatkul text-sm-center">
            <div class="alert alert-danger" role="alert">
                <h1 class="alert-heading">Daftar Kegiatan</h1>
                <p>Daftarkan namamu ke kegiatan yang ada!</p>
                <hr>
            </div>
            </a>
        </div>
    </div>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

storylima/templates/storylima/listMatkul.html
{%load static%}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500;669;800;900&display=swap" rel="stylesheet">

    <style>
      body {
        background-color: #FFFEDF;
        font-family: 'Playfair Display', serif;
      }
      a {
      color: blanchedalmond;
      }
      #back a{
        color: brown;
      }
    </style>

    <title>List Mata Kuliah</title>
  </head>
  <body>

    <div class="row mt-2 mb-3 justify-content-center">
      <div class="col text-center">
        <button id="back" type="button" class="btn btn-outline-warning"><a href="{% url 'personalwebsite:welcome' %}">Kembali ke halaman utama</a></button>
      </div>
    </div>

    <br>

    <h1 style="text-align: center;">{{page_title}}</h1>
    <div class="row mt-2 mb-3">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <table class="table">
                <thead class="thead-dark">
                    <th scope="col">Nama Matkul</th>
                    <th scope="col">Nama Dosen</th>
                    <th scope="col">Jumlah SKS</th>
                    <th scope="col">Semester</th>
                    <th scope="col">Ruang Kelas</th>
                    <th scope="col">Deskripsi</th>
                    <th scope="col">Hapus</th>
                </thead>
                <tbody>
                    {% for post in posts %}
                    <tr>
                        <th>{{post.nama_matkul}}</th>
                        <th>{{post.nama_dosen}}</th>
                        <th>{{post.jumlah_sks}}</th>
                        <th>{{post.semester}}</th>
                        <th>{{post.ruang_kelas}}</th>
                        <th>{{post.deskripsi}}</th>
                        <th><a class="btn btn-danger" href="{% url 'storylima:delete' post.id  %}">Delete</a></th>
                    </tr>
                    {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="col-md-1"></div>
  </div>
  <div class="row mb-3 justify-content-center">
    <div class="col text-center">
      <button type="button" class="btn btn-dark"><a href="{% url 'storylima:add' %}">Tambah Jadwal</a></button>
    </div>
  </div>

 

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>